[project]
name = "io_scene_psk_psa"

[pytest]
blender-addons-dirs = "io_scene_psk_psa"
testpaths = "../tests"

[tool.coverage.run]
branch = true

[tool.coverage.report]
ignore_errors = true

[tool.pyright]
reportInvalidTypeForm = false